apiVersion: v1
kind: Service
metadata:
  name: demo-app-nodejs
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: demo-app-nodejs