replicaCount: 1

image:
  repository: debianmaster/demo-app-nodejs
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: demo-app-nodejs
  port: 3000

resources: {}

nodeSelector: {}

affinity: {}

