name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: ./

    - name: Build Docker image
      run: |
        podman build -t debianmaster/demo-app-nodejs .

    - name: Push Docker image
      run: |
        podman login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        podman push debianmaster/demo-app-nodejs

    - name: Deploy with Helm
      run: |
        helm upgrade --install demo-app-nodejs ./helm --namespace default
