name: CI/CD for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the application
        run: |
          npm run build

      - name: Build Docker image
        run: |
          podman build -t debianmaster/app .

      - name: Push Docker image
        run: |
          podman push debianmaster/app

      - name: Deploy using Helm
        run: |
          helm upgrade --install demo-app-nodejs ./helm
